---
- name: Base configuration
  hosts: all

  roles:
    - macos_components
    - role: homebrew
      vars:
        homebrew_upgrade_packages: true
        homebrew_taps:
          - homebrew/cask-fonts
        homebrew_fonts:
          - font-meslo-lg-nerd-font
        homebrew_formulae:
          - bat
          - name: coreutils
            state: absent
          - htop
        homebrew_casks:
          - fork
    - role: git_repositories
      vars:
        git_repositories_repos:
          - repository: "https://github.com/ohmyzsh/ohmyzsh.git"
            destination: "~/.oh-my-zsh"
            update: false
            version: "master"
          - repository: "https://gitee.com/romkatv/powerlevel10k.git"
            destination: "~/.oh-my-zsh/custom/themes/powerlevel10k"
            update: false
            version: "master"
