---
- name: Base configuration
  hosts: all

  roles:
    - macos_components
    - role: homebrew
      vars:
        homebrew_upgrade_packages: true
        homebrew_taps:
          - homebrew/cask-fonts
        homebrew_fonts:
          - font-meslo-lg-nerd-font
        homebrew_formulae:
          - bat
          - name: coreutils
            state: absent
          - htop
        homebrew_casks:
          - fork
