---
- name: MacOS configuration
  hosts: all
  vars_files:
    - vars/main.yml
  vars:
    brew_packages: "{{ base_packages }}"

  pre_tasks:
    - name: Add optional brew packages
      tags: never, full
      block:
        - name: Add development packages
          ansible.builtin.set_fact:
            brew_packages: "{{ brew_packages + devel_packages }}"
          tags: devel

        - name: Add office packages
          ansible.builtin.set_fact:
            brew_packages: "{{ brew_packages + office_packages }}"
          tags: office

        - name: Add security packages
          ansible.builtin.set_fact:
            brew_packages: "{{ brew_packages + security_packages }}"
          tags: security

        - name: Add virtualization packages
          ansible.builtin.set_fact:
            brew_packages: "{{ brew_packages + v12n_packages }}"
          tags: v12n

        - name: Add navigation packages
          ansible.builtin.set_fact:
            brew_packages: "{{ brew_packages + navi_packages }}"
          tags: navigation

        - name: Add maker packages
          ansible.builtin.set_fact:
            brew_packages: "{{ brew_packages + maker_packages }}"
          tags: maker

  roles:
    - role: macos_components
      tags: always

    - role: homebrew
      vars:
        homebrew_taps: "{{ brew_taps }}"
        homebrew_fonts: "{{ brew_fonts }}"
        homebrew_packages: "{{ brew_packages }}"
      tags: always

    - role: macos_applications
      vars:
        macos_applications_apps: "{{ apps }}"
      tags: mas, never, full

    - role: git_repositories
      vars:
        git_repositories_repos: "{{ git_repos }}"
      tags: always

    - role: macos_config
      vars:
        macos_config_templates: "{{ config_templates }}"
        macos_config_files: "{{ config_files }}"
      tags: always
