---
- name: Temporarily disable the need for a sudo password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ ansible_user_id }} ALL='
    line: '{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  become: true

- name: Install Homebrew
  ansible.builtin.shell:
    cmd: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL {{homebrew_install_script}})"
    creates: "{{ homebrew_binary_path }}/brew"
  become: false

- name: Re-enable the sudo password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ ansible_user_id }} ALL='
    line: '{{ ansible_user_id }} ALL=(ALL) ALL'
    validate: visudo -cf %s
  become: true
