---
- name: Get list of all installed Appstore Apps
  ansible.builtin.command:
    cmd: "{{ macos_applications_mas_binary }} list"
  register: installed_apps
  check_mode: false
  changed_when: false

- name: Ensure Appstore Apps are present
  ansible.builtin.command:
    cmd: "{{ macos_applications_mas_binary }} install {{ item.id | default(item) }}"
  register: mas_result
  with_items: "{{ macos_applications_apps }}"
  when: (item.id | default(item) | string) not in installed_apps.stdout
  changed_when: mas_result.rc == 0
